import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollTopButton from "@/components/ScrollTopButton";
import Image from "next/image";
import Link from "next/link";
import { ChevronDown } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const keywords = [
  { label: "로스트아크골드", value: "lostark-gold", href: "/lostark-gold" },
  { label: "로아골드", value: "loa-gold", href: "/loa-gold" },
  { label: "로아골드시세", value: "loa-gold-price", href: "/loa-gold-price" },
  {
    label: "로스트아크골드시세",
    value: "lostark-gold-price",
    href: "/lostark-gold-price",
  },
  { label: "로아레이드골드", value: "loa-raid-gold", href: "/loa-raid-gold" },
  { label: "로스트아크현질", value: "lostark-cash", href: "/lostark-cash" },
  {
    label: "로아모바일시세",
    value: "loa-mobile-price",
    href: "/loa-mobile-price",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="ko" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="max-w-[1280px] mx-auto absolute top-0 left-1/2 transform -translate-x-1/2 w-full flex xl:justify-between justify-center items-center py-6 z-10">
          <Link href="/">
            <Image
              src="/logo.png"
              className="xl:w-[180px] w-32 flex justify-center items-center"
              alt="로고"
              width={180}
              height={180}
            />
          </Link>
          <nav className="xl:flex hidden gap-10 text-lg font-medium !text-white">
            <div className="dropdown dropdown-bottom dropdown-end dropdown-hover text-white">
              <Link
                href="/trade"
                className="flex cursor-pointer items-center gap-1"
              >
                <span>거래목록</span>
                <ChevronDown />
              </Link>
              <ul className="dropdown-content menu bg-base-100 rounded-box w-52 p-2 shadow-sm">
                {keywords.map((item) => (
                  <li key={item.value}>
                    <Link
                      href={item.href}
                      className="hover:text-yellow-400 transition-colors duration-200"
                    >
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
            <div className="dropdown dropdown-bottom dropdown-end dropdown-hover">
              <Link
                href="/trade"
                className="flex cursor-pointer items-center gap-1"
              >
                <span>거래현황</span>
                <ChevronDown />
              </Link>
              <ul className="dropdown-content menu bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm">
                {keywords.map((item) => (
                  <li key={item.value}>
                    <Link
                      href={item.href}
                      className="hover:text-yellow-400 transition-colors duration-200"
                    >
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
            <Link href="/blog">블로그</Link>
          </nav>
        </header>

        {children}

        <footer className="bg-[#0b0b13] text-white py-20 flex justify-center items-center flex-col gap-2">
          {/* SNS 아이콘 */}
          <div className="flex justify-center gap-5 mb-6">
            <a href="#" className="text-pink-500 hover:scale-110 transition">
              <i className="fab fa-instagram text-2xl"></i>
            </a>
            <a href="#" className="text-blue-500 hover:scale-110 transition">
              <i className="fab fa-facebook text-2xl"></i>
            </a>
            <a href="#" className="text-sky-400 hover:scale-110 transition">
              <i className="fab fa-twitter text-2xl"></i>
            </a>
            <a href="#" className="text-red-500 hover:scale-110 transition">
              <i className="fab fa-youtube text-2xl"></i>
            </a>
            <a href="#" className="text-green-500 hover:scale-110 transition">
              <i className="fab fa-napster text-2xl"></i>
            </a>
            <a href="#" className="text-lime-400 hover:scale-110 transition">
              <i className="fab fa-android text-2xl"></i>
            </a>
            <a href="#" className="text-orange-400 hover:scale-110 transition">
              <i className="fab fa-tiktok text-2xl"></i>
            </a>
          </div>

          {/* 로고 텍스트 */}

          <Image
            src="/logo.png"
            className="xl:w-[210px] w-32 flex justify-center items-center !mb-4"
            alt="로고"
            width={210}
            height={210}
          />

          {/* 정책 링크 */}
          <div className="flex justify-center flex-wrap gap-4 text-gray-400 text-sm mb-3">
            <a href="#" className="hover:text-white">
              이용약관
            </a>
            <span>|</span>
            <a href="#" className="hover:text-white">
              아이템거래약관
            </a>
            <span>|</span>
            <a href="#" className="hover:text-white">
              개인정보취급방침
            </a>
            <span>|</span>
            <a href="#" className="hover:text-white">
              광고/제휴문의
            </a>
          </div>

          {/* 저작권 */}
          <p className="text-gray-500 text-xs tracking-wide">
            COPYRIGHT (C) GAME MARKET. ALL RIGHTS RESERVED.
          </p>

          <ScrollTopButton />
        </footer>
      </body>
    </html>
  );
}
